name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Get version
        run: |
          OLD_AUDIOBOOKSHELF_VERSION=$(jq -r '.version' version.json)
          AUDIOBOOKSHELF_VERSION=$(curl -s "https://api.github.com/repos/advplyr/audiobookshelf/releases/latest" | jq -r .tag_name)
          if [[ ${AUDIOBOOKSHELF_VERSION} =~ ^v[0-9]+ ]]; then
            if [[ ${AUDIOBOOKSHELF_VERSION} != ${OLD_AUDIOBOOKSHELF_VERSION} ]]; then
              echo "${AUDIOBOOKSHELF_VERSION}"
              echo "AUDIOBOOKSHELF_VERSION=${AUDIOBOOKSHELF_VERSION}" >> $GITHUB_ENV
              echo -e "{\n    \""version\"": \""${AUDIOBOOKSHELF_VERSION}\""\n}" > version.json
              echo "build_status=success" >> $GITHUB_ENV
            fi
          fi

      -
        if: env.build_status == 'success'
        uses: stefanzweifel/git-auto-commit-action@7d0ca8f849305c56d36f992cfb1519b1af5b33f8
        with:
          commit_message: "bump: audiobookshelf ${{ env.AUDIOBOOKSHELF_VERSION }}"
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - 
        name: Docker meta
        if: env.build_status == 'success'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/audiobookshelf
          tags: |
            type=raw,value=${{ env.AUDIOBOOKSHELF_VERSION }}
            type=raw,value=latest

      - 
        name: Set Up QEMU
        if: env.build_status == 'success'
        uses: docker/setup-qemu-action@v3

      - 
        name: Set Up Buildx
        if: env.build_status == 'success'
        uses: docker/setup-buildx-action@v3
        
      - 
        name: Login DockerHub
        if: env.build_status == 'success'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        if: env.build_status == 'success'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            AUDIOBOOKSHELF_VERSION=${{ env.AUDIOBOOKSHELF_VERSION }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - 
        name: Docker Hub Description
        if: env.build_status == 'success'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/audiobookshelf
          short-description: A better audiobookshelf image
          readme-filepath: ./README.md
